output_dir: /scratch/m000097/patelas/env_test/ #Replace with your path
peak_file: /projects/m000097/patelas/regulatory_lm/data/ENCFF420VPZ_processed.bed #Replace with your path
genome: /projects/m000097/patelas/regulatory_lm/data/hg38_repeat_lowercase.fa #Replace with your path
model: RegulatoryLM
embedder: InputSeqOnlyEmbedder
encoder: TransformerLMWithROPE
decoder: BERTStyleDecoder
seed: 0
data_format: bed #"bed" or "narrowpeak" depending on what type of data you have
batch_size: 1024
repeat_weight: 0 #how much loss weight to assign long repeat stretches
fourier_loss_weight: 0.002 #weight for Fourier loss
motif_low: 6 #motif size lower bound for Fourier loss
motif_high: 20 #motif size upper bound for Fourier loss
smoothing_factor: 5 #smoothing factor for Fourier loss
min_stretch: 30 #minimum stretch of consecutive repeats above which to downweight
embedding_size: 768
num_encoder_layers: 8 #Number of transformer/convolution/etc. layers
num_epochs: 300
max_jitter: 50
seq_len: 350
mask_prob: 0.15 #probability of masking
early_stopping: false
patience: 7
shuffle: true #shuffle data at every epoch
train_chrom_list:  [
        "chr1",
        "chr2",
        "chr3",
        "chr4",
        "chr7",
        "chr8",
        "chr9",
        "chr11",
        "chr12",
        "chr13",
        "chr15",
        "chr16",
        "chr17",
        "chr19",
        "chrX",
        "chrY"
    ]

valid_chrom_list: [
        "chr6",
        "chr21"
    ]

test_chrom_list: [
        "chr5",
        "chr10",
        "chr14",
        "chr18",
        "chr20",
        "chr22"
    ] #train/test/validation chromosomes

float_dtype: bfloat16 #not used with Fourier loss
num_real_tokens: 4
optimizer: adamw
optimizer_params:
  lr: 1.e-4
  weight_decay: 1.e-6
encoder_kwargs:
  dim_feedforward: 3072 #Feed forward dimension of transformer
  norm_first: false #Whether transformer is "norm first" or "norm last"
