name: ArsenalTesting2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pytorch=2.2.0
  - pytorch-cuda=12.1
  - numpy=1.26.3
  - scipy=1.12.0
  - pandas=2.2.0
  - tqdm=4.66.1
  - h5py=3.10.0
  - scikit-learn=1.4.2
  - pyfaidx=0.7.2.1
  - pybigwig=0.3.22
  - ncls=0.0.68
  - pyyaml=6.0.1
  - transformers=4.44.0
  - pip
  - pip:
      - rotary-embedding-torch==0.8.9
      - modisco-lite
      - mamba-ssm
