channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - pytorch=2.2.0
  - pytorch-cuda=12.1
  - python=3.10
  - numpy=1.26.3
  - scipy=1.12.0
  - pandas=2.2.0
  - tqdm=4.66.1
  - h5py=3.10.0
  - pip=24.0
  - scikit-learn=1.4.2
  - pyfaidx=0.7.2.1
  - pybigwig=0.3.22
  - ncls=0.0.68
  - pyyaml=6.0.1
  - rotary-embedding-torch=0.8.9
  - transformers=4.44.0